[general]

[cdr-test]
exten => _X.,1,Answer()
 same => n,Set(WAIT_TIME=${RAND(5,10)})
 same => n,Verbose(1,CDR test: waiting ${WAIT_TIME}s on ${CHANNEL})
 same => n,Wait(${WAIT_TIME})
 same => n,Hangup()
